# Generated by Django 2.1.4 on 2018-12-24 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClienteBD',
        ),
    ]
